@startuml

skinparam sequenceArrowThickness 5
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor A
participant B
participant C
participant D

A -> B : hello bbbbbbbbbbbbbbbbb
B --> A : hello aaaaaaaaaaaaaaaa

B -> C : hello ccccc
C -> B : hello bbbbbbb

@enduml
